updates:
  - allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: chore
    directory: /
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    reviewers:
      - 'ridedott/platform'
    schedule:
      interval: daily
  - allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: chore
    directory: /
    open-pull-requests-limit: 99
    package-ecosystem: npm
    reviewers:
      - 'ridedott/platform'
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      # Husky version 5 is in early access, with a license for sponsors and open
      # source projects only. After the early access, husky v5 will be MIT.
      - dependency-name: husky
        versions:
          - "5"
version: 2
