env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      '@typescript-eslint/camelcase': off
      max-lines-per-function: off
      no-magic-numbers: off
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
