branding:
  color: gray-dark
  icon: git-merge
description:
  'Automatically merge Pull Requests from the indicated github account.'
inputs:
  GITHUB_LOGIN:
    default: 'dependabot[bot]'
    description: 'The GitHub login for which automatic merges are enabled.'
    required: false
  GITHUB_TOKEN:
    description: 'A GitHub token.'
    required: true
  MERGE_METHOD:
    default: SQUASH
    description:
      'Represents available types of methods to use when merging a pull request.
      One of: MERGE, STASH or REBASE'
    required: false
  PRESET:
    description:
      'Enable additional functionality to better personalize the behavior. One
      of: DEPENDABOT_MINOR or DEPENDABOT_PATCH.'
    required: false
  DISABLED_FOR_MANUAL_CHANGES:
    description:
      'Disable automatic merges for changes made by a different Github login
      than the one set in GITHUB_LOGIN. One of: "true" or "false".'
    default: 'false'
    required: false
name: 'Merge me!'
runs:
  main: dist/index.js
  using: node12
