branding:
  color: gray-dark
  icon: git-merge
description: Automatically merge Pull Requests from various bots.
inputs:
  GITHUB_TOKEN:
    description: A GitHub token.
    required: true
name: Auto merge
runs:
  main: dist/index.js
  using: node12
