name: 'Auto merge'
description:
  'Automatically merge Pull Requests from the indicated github account.'
branding:
  color: 'gray-dark'
  icon: 'git-merge'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token.'
    required: true
  GITHUB_LOGIN:
    description: 'The GitHub login for which automatic merges are enabled.'
    required: false
    default: 'dependabot-preview[bot]'
runs:
  using: 'node12'
  main: 'dist/index.js'
