name: 'Merge me!'
description:
  'Automatically merge Pull Requests from the indicated github account.'
branding:
  color: 'gray-dark'
  icon: 'git-merge'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token.'
    required: true
  GITHUB_LOGIN:
    description: 'The GitHub login for which automatic merges are enabled.'
    required: false
    default: 'dependabot-preview[bot]'
  MERGE_METHOD:
    description:
      'Represents available types of methods to use when merging a pull request.
      One of: MERGE, STASH or REBASE'
    required: false
    default: SQUASH
  MERGE_CATEGORY:
    description:
      'Specify the semantic version category to automatically merge. One of:
      MAJOR, MINOR or PATCH'
    required: false
    default: MAJOR
runs:
  using: 'node12'
  main: 'dist/index.js'
