name: 'Dependabot auto merge'
description: 'Automatically merge Pull Requests from Dependabot.'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
